
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: badges
  username: badges
  password: badges
  host:     localhost


test:
  <<: *default
  database: badges_test
  username: badges
  password: badges
  host:     localhost


